### ISSUE TITLE
Request textDocument/documentLink failed

### ISSUE THREAD

**Issue by OmeGak** [ByPikod/vscode-markdown-alert#1]
Every time that I open a quote block the following error is logged in the Markdown Language Server:

```
[Error - 3:24:58 PM] Request textDocument/documentLink failed.
  Message: Request markdown/parse failed with message: Cannot read properties of undefined (reading 'type')
  Code: -32603 
```

This only happen if the `yahyabatulu.vscode-markdown-alert` extension is enabled.

**Comment by ByPikod** [comment]
Hello! Thank you for your feedback.

I should ask a few questions for solving the issue:

- Have you tried disabling all other extensions except "yahyabatulu.vscode-markdown-alert" to rule out any conflicts with other extensions?
- Have you experienced the same error in a clean, newly created markdown file?
- In which version of VS Code did you encounter the error? (Web / Notebook / Regular)

**Comment by ByPikod** [comment]
Problem solved
https://github.com/ByPikod/markdown-it-github-alert/commit/b48aa0593a07c42464bc2332bb079a3dcf4cfe1e
https://github.com/ByPikod/vscode-markdown-alert/commit/d31b340ad92f55efbd42f86957215934cfc41915
